# Используем базовый образ Node.js для разработки
FROM node:22-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json (если есть) для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci

# Копируем остальные файлы проекта
COPY . .

# Устанавливаем Prisma CLI глобально для разработки
RUN npm install -g prisma

# Генерируем Prisma клиента
RUN npm run prisma:generate

# Открываем порт, который будет использоваться приложением
EXPOSE 3000

# Команда для запуска приложения в режиме разработки
CMD ["sh", "-c", "npm run prisma:push && npm run dev"]
